[project]
name = "pomodoro-timer"
version = "0.1.0"
description = "A modern, customizable Pomodoro timer application built with Python and PyQt6"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "PyQt6>=6.5.0",
    "pygame>=2.5.0",
]
